name: rail-creationz
channels:
  - defaults
dependencies:
  - python=3.7
  - jupyter
  - jupyterlab
  - numpy
  - sphinx
  - matplotlib
  - pandas
  - scipy
  - scikit-learn
  - dill
  - pip
  - pip:
    - corner
    - tensorflow==2.2.0
    - tensorflow-probability==0.10.1
    - jax==0.1.75
    - jaxlib==0.1.52
    - flax==0.2.0
