##########################################################################################
#
# RAIL configuration file for delightPZ module
#
# Steering Delight from RAIL
# Used on Vera C. Rubin LSST only estimation
#
# Author        : Sylvie Dagoret-Campagne
# Affiliation   : IJCLab/IN2P3/CNRS/France
# Creation date : January 4th 2022
# Last update   : January 4th 2022
#
############################################################################################
run_params:
  class_name: delightPZ
  run_name: test_delightPZ
#------------------------------------------------
# redshift range and binning for delight
# dlght_ prepend means a parameter used by Delight
#------------------------------------------------
  dlght_redshiftMin: 0.01
  dlght_redshiftMax: 3.01
  dlght_redshiftNumBinsGPpred: 301
  dlght_redshiftBinSize: 0.01
  dlght_redshiftDisBinSize: 0.2
#-----------------------------------------------
# Delight input data (Filters and SED templates), note Delight will write inside this directory
# example recommended:
# - DC2 mode : dlght_inputdata: "./tmp/delight_indata"
# - tutorial mode : dlght_inputdata: "./tmpsim/delight_indata"
#----------------------------------------------
  dlght_inputdata: "./tmpsim/delight_indata"
#---------------------------------------
# temporary directory for delight work
# example recommended:
# - DC2 mode : tempdir: "./tmp" and tempdatadir: "./tmp/delight_data"
# - tutorial mode : tempdir: "./tmpsim" and tempdatadir: "./tmpsim/delight_data"
#---------------------------------------
  tempdir: "./tmpsim"
  tempdatadir: "./tmpsim/delight_data"
#---------------------------------------
# new stuff added Nov 2021
#---------------------------------------
# FOR FILTERS:
  bands_names: "DC2LSST_u DC2LSST_g DC2LSST_r DC2LSST_i DC2LSST_z DC2LSST_y"
  bands_path: "../../rail/estimation/data/FILTER"
  bands_fmt: "res"
  bands_numcoefs: 15
  bands_verbose: True
  bands_makeplots: False
  bands_debug: True
# FOR SEDS:
  sed_path: "../../rail/estimation/data/SED"
  sed_name_list: "El_B2004a Sbc_B2004a Scd_B2004a SB3_B2004a SB2_B2004a Im_B2004a ssp_25Myr_z008 ssp_5Myr_z008"
  sed_fmt: "sed"
  prior_t_list: "0.27 0.26 0.25 0.069 0.021 0.11 0.0061 0.0079"
  prior_zt_list: "0.23 0.39 0.33 0.31 1.1 0.34 1.2 0.14"
  lambda_ref: 4500.
# Training stuff
  train_refbandorder: "DC2LSST_u DC2LSST_u_var DC2LSST_g DC2LSST_g_var DC2LSST_r DC2LSST_r_var DC2LSST_i DC2LSST_i_var DC2LSST_z DC2LSST_z_var DC2LSST_y DC2LSST_y_var redshift"
  train_refband: DC2LSST_i
  train_fracfluxerr: 1.e-4
  train_xvalidate: False
  train_xvalbandorder: "_ _ _ _ DC2LSST_r DC2LSST_r_var _ _ _ _ _ _"
# Target stuff
  target_refbandorder: "DC2LSST_u DC2LSST_u_var DC2LSST_g DC2LSST_g_var DC2LSST_r DC2LSST_r_var DC2LSST_i DC2LSST_i_var DC2LSST_z DC2LSST_z_var DC2LSST_y DC2LSST_y_var redshift"
  target_refband: DC2LSST_r
  target_fracfluxerr: 1.e-4
#----------------------------------------
# delight configuration file filename
#----------------------------------------
  delightparamfile: "parametersTest.cfg"
#------------------------------------------------------------------------
# Running mode
# tutorial mode :
#   - True  : activate internal flux simulation
#   - False : activate use of DC2 datasets for training and Validation
#-----------------------------------------------------------------------
  dlght_tutorialmode: True
#------------------------------------------------------------------------
# Filtering of training and Validation dataset
# according flux SNR
#-------------------------------------------------------------------------
  flag_filter_training: True
  snr_cut_training: 5
  flag_filter_validation: True
  snr_cut_validation: 3
#-----------------------------------------------------------------------
# Special run
# Should not be used
#-------------------------------------------------------------------------
  dlght_calibrateTemplateMixturePrior: False
#-------------------------------------------------------------------------
# Delight hyper-parameters that must be optimized
#---------------------------------------------------------------------------
  zPriorSigma: 0.2
  ellPriorSigma: 0.5
  fluxLuminosityNorm: 1.0
  alpha_C: 1.0e3
  V_C: 0.1
  alpha_L: 1.0e2
  V_L: 0.1
  lineWidthSigma: 20

