run_params:
  class_name: PZFlowPDF
  run_name: test_PZFlowPDF
  zmin: 0.0
  zmax: 3.0
  nzbins: 301
  flow_seed: 0
  ref_column_name: mag_i_lsst
  column_names: ['mag_u_lsst', 'mag_g_lsst', 'mag_r_lsst', 'mag_i_lsst', 'mag_z_lsst', 'mag_y_lsst']
  mag_limits:
    mag_u_lsst: 27.79
    mag_g_lsst: 29.04
    mag_r_lsst: 29.06
    mag_i_lsst: 28.62
    mag_z_lsst: 27.98
    mag_y_lsst: 27.05
  include_mag_errors: False
  error_names_dict:
    mag_err_u_lsst: "mag_u_lsst_err"
    mag_err_g_lsst: "mag_g_lsst_err"
    mag_err_r_lsst: "mag_r_lsst_err"
    mag_err_i_lsst: "mag_i_lsst_err"
    mag_err_z_lsst: "mag_z_lsst_err"
    mag_err_y_lsst: "mag_y_lsst_err"
  n_error_samples: 3
  soft_sharpness: 10
  soft_idx_col: 0
  redshift_column_name: redshift
  num_training_epochs: 50
  inform_options: {'save_train': True, 'load_model': False, 'modelfile': 'PZflowPDF.pkl'}
