run_params:
  class_name: simpleNN
  run_name: test_simpleNN
  width: 0.025
  zmin: 0.0
  zmax: 3.0
  nzbins: 301
  inform_options: {'save_train': False, 'modelfile': 'simpleNN.pkl', 'load_model': False}


