config: pipe_example_config.yml
inputs:
  model: /Users/echarles/software/DESC/RAIL/src/rail/examples/goldenspike/data/pretrained_flow.pkl
log_dir: tmp_out
modules: rail
output_dir: tmp_out
resume: false
site:
  dry_run: false
  max_threads: 2
  name: local
  python_paths: []
stages:
- classname: FlowCreator
  module_name: rail.creation.engines.flowEngine
  name: flow_engine_test
  nprocess: 1
- classname: LSSTErrorModel
  module_name: rail.creation.degradation.lsst_error_model
  name: lsst_error_model_test
  nprocess: 1
- classname: ColumnMapper
  module_name: rail.core.utilStages
  name: col_remapper_test
  nprocess: 1
- classname: TableConverter
  module_name: rail.core.utilStages
  name: table_conv_test
  nprocess: 1
