run_params:
  class_name: flowCreator
  run_name: test_flowCreator
  flow_seed: 0
  phys_cols:
    "redshift": [0., 3.]
  phot_cols:
    "u": [22.79, 27.79]
    "g": [24.04, 29.04]
    "r": [24.06, 29.06]
    "i": [23.62, 28.62]
    "z": [22.98, 27.98]
    "y": [22.05, 27.05]
  calc_colors:
    ref_column_name: r
  spline_knots: 16
  num_training_epochs: 30
  modelfile': "example_flow.pkl"
